apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: ako-operator.community.tanzu.vmware.com.1.5.0
  namespace: ako-operator
spec:
  refName: ako-operator.community.tanzu.vmware.com
  version: 1.5.0
  releaseNotes: "ako-operator 1.5.0"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/ako-operator@sha256:e723cae7924b7caec70771a92e3d0aea7c14df4829e8cbaba19e4b0e5315cba2
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
