apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.4.0-rc.1
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.4.0-rc.1
  releaseNotes: "vsphere-csi 2.4.0-rc.1 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.4.0-rc.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:1f85817c27af93854363503e70926b7f82fe8f5dafec7733b8071b5203e87444
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
