apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.3.0
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.3.0
  releaseNotes: "vsphere-csi 2.3.0 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.3.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:8bc29eb85b7bd5cba9257dbdb051ba816fb82a868d0d5a1efeffeb947429cd81
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
