apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: kapp-controller.community.tanzu.vmware.com.0.21.0
  namespace: kapp-controller
spec:
  refName: kapp-controller.community.tanzu.vmware.com
  version: 0.21.0
  releaseNotes: "kapp-controller 0.21.0 https://github.com/vmware-tanzu/carvel-kapp-controller"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/kapp-controller@sha256:ef02c13cacf1f98c9ec43f03f71c882778539862de7cce85b0c02eb75c8ea374
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
